version: '3.0'
services:
  mergiss:
    build:
      context: .
    container_name: mergiss_mergiss
    ports:
      - 5173:5173
    volumes:
      - ./:/app
    command: npm run dev
#    command: tail -F anything
    tty: true
