services:
  mergiss:
    build:
      context: .
      args:
        NODE_ENV: development
    container_name: mergiss_mergiss
    ports:
      - 5173:5173
    volumes:
      - ./:/app
    command: npm run dev
    tty: true
