<MDialog icon="settings" title={leetize("SETTINGS")} subTitle="version: v{versionString}">

  {#snippet activator()}
    <MAppBarButton icon="settings" />
  {/snippet}

  <div class="settings-text">
    Mergiss was born as a tetris-like game idea. The idea has pivoted since, into what you see.
  </div>

  <div class="settings-text">
    The app first served just a test bed to try real life viability of a rotating alghorytm. TLDR: it still powers the game.
  </div>

  <div class="settings-text">
    As of today Mergiss serves as test bed for vibe coding, analytics, and LLM fraud detection.
  </div>

  <div class="settings-text">
    Some modules have up to 90% of code simply generated by LLMs, and various NPM libraries were created 100% (lui-g, html-trajectory, iterators).
  </div>

  </MDialog>

<script>

  import MAppBarButton from "$lib/components/MAppBarButton.svelte";
  import { version } from '$app/environment';
  import MDialog from "$lib/components/MDialog.svelte";
  import { leetize } from "$lib/../util/texts";

  let versionString = $derived(version.split('.').slice(0, 2).join('.'));

</script>

<style>
  .settings-text {
      max-width: 50vw;
      margin-bottom: calc(2vh + 0.5vw);
  }
</style>
